### ISSUE TITLE
Ошибка формирования пути для категорий

### ISSUE THREAD

**Issue by noldor** [rb2/opencart-seopro#13]
Когда скрипт разбирает параметр path в данном коде (строка 312-318):

``` php
case 'path':
    $categories = explode('_', $value);
    foreach ($categories as $category) {
        $queries[] = 'category_id=' . $category;
    }
    unset($data[$key]);
    break;
```

Использует все id категорий которые присутствуют в url:
path=2_4_1_2_3
site.ru/category2/category4/category1/category2/category3/
Хотя дерево категорий - 1->2->3
getPathByCategory не используется, а при разборе url вида site.ru/index.php?route=product/category&path=12_13_1_2_12 обрабатывает правильно.
На сайте появились дубли страниц (возможно из-за того, что раньше версия oc была 1.5.5), поэтому пришлось переделать немного скрипт.

``` php
case 'path':
    $category_path = explode('_', $value);
    $category_id = end($category_path);
    $categories = $this->getPathByCategory($category_id);
    $categories = explode('_', $categories);
    foreach ($categories as $category) {
        $queries[] = 'category_id=' . $category;
    }
    unset($data[$key]);
    break;
```

**Comment by rb2** [comment]
Спасибо за помощь и пардон за задержку - я помню и как только доберусь до Seopro, внесу этот фикс!
