### ISSUE TITLE
Не удаляется товар из корзины, при включеном модуле SeoPro.

### ISSUE THREAD

**Issue by ghost** [rb2/opencart-seopro#15]
Не удаляется товар из корзины, при включеном модуле SeoPro. После нажатия на крестик удаления товара из корзины товар не удаляется, сумма заказа не пересчитывается до обновления страницы.
Текущая сборка ocStore 2.1.0.2 (чистая, без правок).
##

**Comment by stefanio** [comment]
У меня тоже самое.

**Comment by rb2** [comment]
Не воспроизводится. Проверял на opencartjazz.com; страница корзины с ЧПУ.

ocStore не использует мой вариант сеопро, чем-то не понравился, решили пилить свой. В итоге теперь существует несколько вариантов, а изменения не синхронизируются в один OCMOD-пакет.
