### ISSUE TITLE
agreement check-box, the page pop up that should have to  appear does not appear, or appear broken

### ISSUE THREAD

**Issue by rb2** [rb2/opencart-seopro#5]
oc2011. When a client wants to read the "Terms of use", in any page that has an agreement check-box, the page pop up that should have to  appear does not appear, or appear broken. So I deleted the SEO URL from the page "Terms of use" and everything  is OK now, except that I don't have nice url anymore for this page... For example:
`../store/index.php?route=information/information/agree&amp;information_id=5`

**Comment by ose1955** [comment]
Fixed
