### ISSUE TITLE
When I use "Search engine" in the second language that I have, redirects every time in default language

### ISSUE THREAD

**Issue by rb2** [rb2/opencart-seopro#6]
When I use "Search engine" in the second language that I have, redirects every time in default language. I deleted SEO URL for  "Search engine" too but I Keep have the same redirect. Only if I  disable SEOPRO things goes normal. This is the most important problem!

**Comment by ose1955** [comment]
Fixed. I have change the language detecting to the algorithm similar to the `index.php`. Please check
