### ISSUE TITLE
Some pages not valid in W3C due to HTML entities (amp) not properly encoded

### ISSUE THREAD

**Issue by rb2** [rb2/opencart-seopro#7]
some pages are not valid in W3C because of  an [&] that did not start a character reference. (`&` probably should  have been escaped as `&amp;`) For example: `.. type="hidden"  name="redirect_query"
value="&path=116_117_118&product_id=52" />`

**Comment by ose1955** [comment]
This is not SEOPRO but native oc1xxx..oc2xxx error. Fixed for SEOPRO but should be propagated on all versions as bugfix.
